spring:
  application:
    name: receipt-service
  datasource:
    url: jdbc:sqlserver://localhost:3333;databaseName=fm_dev
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: fm_login
    password: Passw0rd!
    platform: SqlServer
#    initialization-mode: always
#    data: classpath:data.sql
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    database: sql-server
    show-sql: true
#    hibernate.ddl-auto: create
    hibernate.ddl-auto: update
  #    properties.hibernate.hbm2ddl.import_files: classpath:/data/sql/food_nutrition_bulk.sql #,classpath:/data/sql/food_items_bulk.sql,classpath:/data/sql/nutrition_rda_data/lifestagegroup_data.sql, classpath:/data/sql/nutrition_rda_data/nutritionRDA_data.sql
#    generate-ddl: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


firebase:
  credential:
    resource-path: food-manager-bb596-firebase-adminsdk-asq3n-98af5fc484.json

server:
  port: 8081

data:
  -
    runOnUpdate: false
    path: data/sql/lifestagegroup_data.sql
  -
    runOnUpdate: false
    path: data/sql/nutritionRDA_data.sql
  -
    runOnUpdate: false
    path: data/sql/food_nutrition_bulk.sql
  -
    runOnUpdate: false
    path: data/sql/food_items_bulk.sql

#
#auth0:
#  audience: receipt-service

#okta:
#  oauth2:
#    issuer: https://dev-588838-admin.okta.com/oauth2/default
#    clientId: 0oajphh3qFDXTZ0nF4x6
#    clientSecret: A_2BfSgSbLihpVQiRy22xNT8iPYBZ1Wlfj_37-3V
#    scopes: openid