export const AUTH_USER = 'auth_user';
export const AUTH_ERROR = 'auth_error';

export const UPLOAD_RECEIPT = 'UPLOAD_RECEIPT';
export const FETCH_RECEIPTS = 'FETCH_RECEIPTS';
export const FETCH_RECEIPT = 'FETCH_RECEIPT';
export const FETCH_RECEIPT_IMAGE = 'FETCH_RECEIPT_IMAGE';
export const EDIT_RECEIPT_ITEM = 'EDIT_RECEIPT_ITEM';
export const EDIT_RECEIPT_ITEMS = 'EDIT_RECEIPT_ITEMS';
export const DELETE_RECEIPT = 'DELETE_RECEIPT';

//FEEDBACK
export const LOADING = "LOADING";
export const DIALOG_LOADING = "DIALOG_LOADING";
export const START_BATCH_LOADING = "START_BATCH_LOADING";
export const STOP_BATCH_LOADING = "STOP_BATCH_LOADING";
export const MESSAGE = 'MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const SET_CURRENT_RECEIPT = 'SET_CURRENT_RECEIPT';
export const FETCH_RECEIPT_ITEMS = 'FETCH_RECEIPT_ITEMS';

export const FETCH_FOOD_ITEMS = 'FETCH_FOOD_ITEMS';
export const CLEAR_FOOD_ITEMS = 'CLEAR_FOOD_ITEMS';
export const FOOD_LOADING = "FOOD_LOADING";

export const ADD_RECEIPT_ITEMS_TO_FOODSTOCK = 'ADD_RECEIPT_ITEMS_TO_FOODSTOCK';
export const FETCH_FOODSTOCK = 'FETCH_FOODSTOCK';
export const UPDATE_FOODSTOCK = 'UPDATE_FOODSTOCK';
export const DELETE_FOODSTOCK = 'DELETE_FOODSTOCK';
export const ADD_ITEM_FOODSTOCK = 'ADD_ITEM_FOODSTOCK';
export const EAT_ITEM_FOODSTOCK = 'EAT_ITEM_FOODSTOCK';

export const FETCH_NUTRITION_STATE = 'FETCH_NUTRITION_STATE';
export const FETCH_NUTRITION_RDA = 'FETCH_NUTRITION_RDA';
export const FETCH_ACTIVITY_FACTORS = 'FETCH_ACTIVITY_FACTORS';
export const UPDATE_USER_STATE = 'UPDATE_USER_STATE';



