#FROM node:14.16.0-alpine3.13
#WORKDIR /app
#
#COPY ./react-client/build /app
#ENV PATH /app/node_modules/.bin:$PATH
#EXPOSE 5000
#ENTRYPOINT ["serve", "-s", "build", "-l", "5000"]

FROM nginx:stable-alpine
COPY ./react-client/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]