FROM azul/zulu-openjdk:13
#FROM openjdk:13-jdk-alpine
#RUN addgroup -S spring && adduser -S spring -G spring
#USER spring:spring

EXPOSE 9090

#RUN apk add --no-cache --virtual build-dependencies python3 --update py3-pip\
#&& apk add --virtual build-runtime build-base python3-dev tesseract-ocr\
#openblas-dev freetype-dev pkgconfig gfortran\
#&& ln -s /usr/include/locale.h /usr/include/xlocale.h\
#&& pip3 install --upgrade pip\
#&& pip3 install --no-cache-dir pyspellchecker nltk

RUN apt-get update\
 && apt-get -y install g++ autoconf automake libtool pkg-config libpng-dev libjpeg8-dev\
 libtiff5-dev zlib1g-dev tesseract-ocr\
 && apt-get -y install python3-pip\
# && pip3 install --upgrade pip\
 && pip3 install pyspellchecker nltk

ARG DEPENDENCY=./fm-server/target/dependency
COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY ${DEPENDENCY}/META-INF /app/META-INF
COPY ${DEPENDENCY}/BOOT-INF/classes /app

#COPY ./docker/wait-for-db.sh ./
ENTRYPOINT ["java","-cp","app:app/lib/*","com.dng.foodmanager.receiptservice.ReceiptServiceApp"]

#ARG JAR_FILE=target/*.jar
#COPY ${JAR_FILE} app.jar
#ENTRYPOINT ["./wait-for-db.sh", "--", "java","-jar","/app.jar"]


